### PR TITLE
Use 0 as seed instead of current time in date calculations

### PR DESCRIPTION
**Pull request by leiserfg**

### CODE REVIEW

**Comment by leiserfg** [comment]
See https://github.com/monaqa/dial.nvim/issues/49

**Comment by monaqa** [comment]
Thank you so much!
I didn't take into account that the increment/decrement results would vary depending on the time when the operation was performed.

I would like to discuss one thing. I agree that the time should be fixed, but I don't think the date should.
It's because, when inc/dec a date of the form `"%m/%d"`, the year of the date should be assumed as the year in which the operation was performed.
For example, if you perform an increment operation of the date "02/28" in the year 2024, the result should be "02/29", not "03/01".
What do you think?

**Comment by leiserfg** [comment]
Make sense, so maybe using `os.date("*t", 0)` and updating the year and month to those from `os.date("*t", os.time())` will do the trick?

**Comment by monaqa** [comment]
Sounds good! Could you please modify the code according to the policy?

**Review by monaqa — COMMENTED** [review]
Thank you for the change!
Do we need `.luarc.json`? Maybe you added it by accident.

**Comment by leiserfg** [comment]
Yes, I did, sorry.

**Comment by monaqa** [comment]
No problem. Thanks!

**Pull request merged**
